global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
  
  - job_name: 'elective-web-auth'
    static_configs:
      - targets: ['elective-web-auth:3000']

  - job_name: 'elective-web-restauration'
    static_configs:
      - targets: ['elective-web-restauration:3002']

  - job_name: 'elective-web-order'
    static_configs:
      - targets: ['elective-web-order:3001']